# Porta (Railway injeta a variável PORT automaticamente)
server.port=${PORT:8080}
# Estoque máximo por dia
estoque.limite-diario=30
# CORS ? coloque aqui o domínio do seu site quando estiver em produção
cors.allowed-origins=*
# Admin
admin.senha=suasenhaaqui
admin.token=melreal-admin-2026